import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {SqliteStore} from '../helpers/sqlite-store.ts';
import {previewBooking,previewChange,approve,execute,setFault,editCalendar,resolveConflict,transact,available} from '../../src/lib/bookings/engine.ts';
import type {Operation} from '../../src/lib/bookings/model.ts';
const args=()=>({workshopId:'photography',seats:2,camera:true,calendar:true,requestKey:crypto.randomUUID()});
async function book(s:SqliteStore){const p=await previewBooking(s,args());await approve(s,p.id,p.revision);await execute(s,p.id);return p;}
async function apply(s:SqliteStore,p:Operation){await approve(s,p.id,p.revision);return execute(s,p.id);}
test('preview reserves nothing; no approval means no execution',async()=>{const s=new SqliteStore();const p=await previewBooking(s,args());assert.equal((await s.read()).data.records.length,0);await assert.rejects(execute(s,p.id),/approve/i);assert.equal((await s.read()).data.records.length,0);});
test('approved booking creates three records and persists action receipts',async()=>{const s=new SqliteStore();const p=await book(s);const d=(await s.read()).data;assert.equal(d.records.filter(r=>r.active).length,3);assert.equal(d.operations.find(o=>o.id===p.id)?.status,'completed');assert.equal(available(d,'photography','workshop'),6);assert.ok(d.timeline.some(t=>t.title==='Your plan is confirmed'));});
test('repeat execution and same preview key do not duplicate effects',async()=>{const s=new SqliteStore();const a=args();const p=await previewBooking(s,a);assert.equal((await previewBooking(s,a)).id,p.id);await apply(s,p);await execute(s,p.id);assert.equal((await s.read()).data.records.length,3);await assert.rejects(previewBooking(s,{...a,seats:3}),/different arguments/);});
test('new preview invalidates the old approval',async()=>{const s=new SqliteStore();const p=await previewBooking(s,args());await approve(s,p.id,p.revision);await previewBooking(s,args());await assert.rejects(execute(s,p.id),/review/);assert.equal((await s.read()).data.records.length,0);});
test('wrong revision and expired preview are rejected',async()=>{const s=new SqliteStore();const p=await previewBooking(s,args());await assert.rejects(approve(s,p.id,crypto.randomUUID()),/changed/);await transact(s,d=>{d.operations[0].expiresAt='2000-01-01T00:00:00Z';});await assert.rejects(approve(s,p.id,p.revision),/expired/);});
test('removing camera preserves seats and updates calendar',async()=>{const s=new SqliteStore();await book(s);const p=await previewChange(s,{mode:'remove_camera',requestKey:crypto.randomUUID()});await apply(s,p);const d=(await s.read()).data;assert.equal(d.records.filter(r=>r.active&&r.kind==='workshop').length,1);assert.equal(d.records.filter(r=>r.active&&r.kind==='equipment').length,0);assert.equal(d.records.find(r=>r.kind==='calendar')?.note,'Bring your own camera.');});
test('selective undo keeps workshop and removes camera and calendar',async()=>{const s=new SqliteStore();await book(s);await apply(s,await previewChange(s,{mode:'undo_keep_workshop',requestKey:crypto.randomUUID()}));assert.deepEqual((await s.read()).data.records.filter(r=>r.active).map(r=>r.kind),['workshop']);});
test('undo all releases capacity',async()=>{const s=new SqliteStore();await book(s);await apply(s,await previewChange(s,{mode:'undo_all',requestKey:crypto.randomUUID()}));const d=(await s.read()).data;assert.equal(d.records.filter(r=>r.active).length,0);assert.equal(available(d,'photography','workshop'),8);});
for(const f of ['before','after'] as const)test(`timeout ${f} commit reconciles without duplicate reservations`,async()=>{const s=new SqliteStore();await setFault(s,f);const p=await book(s);let d=(await s.read()).data;assert.equal(d.operations[0].status,'awaiting_resolution');assert.equal(d.records.filter(r=>r.kind==='equipment').length,f==='before'?0:1);await execute(s,p.id,true);await execute(s,p.id,true);d=(await s.read()).data;assert.equal(d.operations[0].status,'completed');assert.equal(d.records.filter(r=>r.kind==='equipment').length,1);assert.equal(d.records.filter(r=>r.kind==='workshop').length,1);});
test('unknown outcomes must be reconciled before correction',async()=>{const s=new SqliteStore();await setFault(s,'after');await book(s);await assert.rejects(previewChange(s,{mode:'undo_all',requestKey:crypto.randomUUID()}),/Check the uncertain/);});
test('manual edit before preview is detected and preserving it needs fresh approval',async()=>{const s=new SqliteStore();await book(s);const r=(await s.read()).data.records.find(r=>r.kind==='calendar')!;await editCalendar(s,r.id,'My custom event','Bring my own notes',r.version);const p=await previewChange(s,{mode:'remove_camera',requestKey:crypto.randomUUID()});assert.equal(p.actions[0].status,'conflict');await assert.rejects(approve(s,p.id,p.revision),/conflict/);const revised=await resolveConflict(s,p.id,'preserve');assert.notEqual(revised.revision,p.revision);await assert.rejects(approve(s,p.id,p.revision),/changed/);await apply(s,revised);const d=(await s.read()).data;assert.equal(d.records.find(x=>x.id===r.id)?.note,'Bring my own notes');assert.equal(d.records.filter(r=>r.active&&r.kind==='equipment').length,0);});
test('manual edit after approval is protected at execution time',async()=>{const s=new SqliteStore();await book(s);const p=await previewChange(s,{mode:'remove_camera',requestKey:crypto.randomUUID()});await approve(s,p.id,p.revision);const r=(await s.read()).data.records.find(r=>r.kind==='calendar')!;await editCalendar(s,r.id,'Edited after preview','Do not erase',r.version);const result=await execute(s,p.id);assert.equal(result.status,'awaiting_resolution');assert.equal(result.actions[0].status,'conflict');assert.equal((await s.read()).data.records.find(x=>x.id===r.id)?.note,'Do not erase');});
test('including current event requires new approval',async()=>{const s=new SqliteStore();await book(s);const r=(await s.read()).data.records.find(r=>r.kind==='calendar')!;await editCalendar(s,r.id,'Custom title','Custom note',r.version);const p=await previewChange(s,{mode:'remove_camera',requestKey:crypto.randomUUID()});const revised=await resolveConflict(s,p.id,'include_current');await assert.rejects(execute(s,p.id),/approve/);await apply(s,revised);assert.equal((await s.read()).data.records.find(x=>x.id===r.id)?.title,'Custom title');});
test('failed cancellation can resume without repeating earlier changes',async()=>{const s=new SqliteStore();await book(s);await setFault(s,'compensation');const p=await previewChange(s,{mode:'undo_all',requestKey:crypto.randomUUID()});const paused=await apply(s,p);assert.equal(paused.status,'awaiting_resolution');await execute(s,p.id,true);assert.equal((await s.read()).data.records.filter(r=>r.active).length,0);});
test('parallel execution of same operation remains idempotent',async()=>{const s=new SqliteStore();const p=await previewBooking(s,args());await approve(s,p.id,p.revision);await Promise.all([execute(s,p.id),execute(s,p.id)]);assert.equal((await s.read()).data.records.length,3);});
test('stale availability cannot oversell',async()=>{const s=new SqliteStore();const p=await previewBooking(s,{...args(),seats:8});await approve(s,p.id,p.revision);await transact(s,d=>{d.records.push({id:'other',kind:'workshop',workshopId:'photography',quantity:2,title:'Other reservation',note:'',version:1,active:true,createdBy:'other',updatedBy:'other'});});const result=await execute(s,p.id);assert.equal(result.status,'awaiting_resolution');assert.equal(available((await s.read()).data,'photography','workshop'),6);});
test('SQLite restart retains unknown outcome and can reconcile',async()=>{const dir=mkdtempSync(join(tmpdir(),'second-take-'));try{let s=new SqliteStore(join(dir,'test.db'));await setFault(s,'after');const p=await book(s);s.close();s=new SqliteStore(join(dir,'test.db'));assert.equal((await s.read()).data.operations[0].status,'awaiting_resolution');await execute(s,p.id,true);assert.equal((await s.read()).data.records.length,3);s.close();}finally{rmSync(dir,{recursive:true,force:true});}});
test('session ownership prevents access to another operation',async()=>{const dir=mkdtempSync(join(tmpdir(),'second-take-'));try{const file=join(dir,'test.db');const a=new SqliteStore(file,'a'),b=new SqliteStore(file,'b');const p=await previewBooking(a,args());await assert.rejects(approve(b,p.id,p.revision),/not found/);await assert.rejects(execute(b,p.id),/not found/);assert.equal((await b.read()).data.records.length,0);a.close();b.close();}finally{rmSync(dir,{recursive:true,force:true});}});
