import {z} from 'zod';
import {previewServiceBooking,previewServiceCancellation,executeServicePlan,serviceBookingSchema} from './services.ts';
import {available,previewBooking,previewChange,execute} from './engine.ts';
import type {Store} from './model.ts';
import {DomainError} from './model.ts';
import {operationEvidence} from './evidence.ts';
const key=z.string().min(8).max(120);const uuid=z.string().uuid();
export const bookingSchema=z.object({workshopId:z.enum(['photography','street','light']),seats:z.number().int().min(1).max(8),camera:z.boolean(),calendar:z.boolean(),requestKey:key,request:z.string().max(1000).optional()}).strict();
const changeSchema=z.object({mode:z.enum(['remove_camera','undo_keep_workshop','undo_all']),sourceId:uuid.optional(),preserveCalendar:z.boolean().optional(),requestKey:key,request:z.string().max(1000).optional()}).strict();
const operationSchema=z.object({operationId:uuid}).strict();
const defs=[
 {name:'preview_service_booking',title:'Preview a simulated reservation',description:'Stage a restaurant, appointment or event reservation or change. Never contacts real providers. Requires browser approval before execution.',inputSchema:{type:'object',properties:{service:{type:'string',enum:['restaurant','appointment','event']},venue:{type:'string'},location:{type:'string'},date:{type:'string',description:'YYYY-MM-DD'},time:{type:'string',description:'24-hour HH:mm'},timeZone:{type:'string',description:'IANA zone'},people:{type:'integer',minimum:1,maximum:12},requestKey:{type:'string',minLength:8},reservationId:{type:'string',format:'uuid'},expectedVersion:{type:'integer',minimum:1}},required:['service','venue','location','date','time','timeZone','people','requestKey'],additionalProperties:false},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false}},
 {name:'preview_service_cancellation',title:'Preview a reservation cancellation',description:'Stage cancellation of one exact simulated reservation. Requires browser approval.',inputSchema:{type:'object',properties:{reservationId:{type:'string',format:'uuid'},requestKey:{type:'string',minLength:8}},required:['reservationId','requestKey'],additionalProperties:false},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false}},
 {name:'execute_service_plan',title:'Execute an approved simulated reservation plan',description:'Apply only the already approved plan. Repeated calls do not repeat a completed effect.',inputSchema:{type:'object',properties:{planId:{type:'string',format:'uuid'}},required:['planId'],additionalProperties:false},annotations:{readOnlyHint:false,destructiveHint:true,idempotentHint:true,openWorldHint:false}},
 {name:'list_service_reservations',title:'Read simulated reservations',description:'Read this workspace’s restaurant, appointment and event reservations and plans.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false}},
 {name:'list_workshops',title:'Browse workshops',description:'Read workshops and remaining capacity in this isolated demo workspace.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false}},
 {name:'preview_booking',title:'Preview a booking',description:'Stage an immutable plan for browser approval. Does not reserve inventory. Reuse requestKey only for identical arguments.',inputSchema:{type:'object',properties:{workshopId:{type:'string',enum:['photography','street','light']},seats:{type:'integer',minimum:1,maximum:8},camera:{type:'boolean'},calendar:{type:'boolean'},requestKey:{type:'string',minLength:8,maxLength:120},request:{type:'string',maxLength:1000}},required:['workshopId','seats','camera','calendar','requestKey'],additionalProperties:false},annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true,openWorldHint:false}},
 {name:'preview_change',title:'Preview a correction or reversal',description:'Stage a selective change to a booking. Resolve unknown outcomes first. Requires fresh browser approval.',inputSchema:{type:'object',properties:{mode:{type:'string',enum:['remove_camera','undo_keep_workshop','undo_all']},sourceId:{type:'string',format:'uuid'},preserveCalendar:{type:'boolean'},requestKey:{type:'string',minLength:8,maxLength:120},request:{type:'string',maxLength:1000}},required:['mode','requestKey'],additionalProperties:false},annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true,openWorldHint:false}},
 ...['get_operation','execute_approved_plan','reconcile_operation'].map(name=>({name,title:name.split('_').join(' '),description:name==='get_operation'?'Read confirmed and unresolved actions.':name==='execute_approved_plan'?'Execute an exact plan already approved in the browser. Approval cannot be granted through MCP. Repeated calls do not duplicate effects.':'Reconcile and resume an approved incomplete operation. Query an existing reservation before retrying. May complete remaining approved actions.',inputSchema:{type:'object',properties:{operationId:{type:'string',format:'uuid'}},required:['operationId'],additionalProperties:false},annotations:{readOnlyHint:name==='get_operation',destructiveHint:name!=='get_operation',idempotentHint:true,openWorldHint:false}}))
];
export const toolDefinitions=defs;
export async function callTool(store:Store,name:string,args:unknown){
 if(name==='preview_service_booking')return {servicePlan:await previewServiceBooking(store,serviceBookingSchema.parse(args))};
 if(name==='preview_service_cancellation'){const a=z.object({reservationId:uuid,requestKey:key}).strict().parse(args);return {servicePlan:await previewServiceCancellation(store,a.reservationId,a.requestKey)};}
 if(name==='execute_service_plan'){const a=z.object({planId:uuid}).strict().parse(args);return {servicePlan:await executeServicePlan(store,a.planId)};}
 if(name==='list_service_reservations'){z.object({}).strict().parse(args);const s=(await store.read()).data;return {reservations:s.reservations??[],plans:s.servicePlans??[]};}
 if(name==='list_workshops'){z.object({}).strict().parse(args);const s=(await store.read()).data;return {workshops:s.workshops.map(w=>({...w,seatsAvailable:available(s,w.id,'workshop'),camerasAvailable:available(s,w.id,'equipment')}))};}
 if(name==='preview_booking')return {operation:await previewBooking(store,bookingSchema.parse(args)),approvalPath:'/'};
 if(name==='preview_change')return {operation:await previewChange(store,changeSchema.parse(args)),approvalPath:'/'};
 const {operationId}=operationSchema.parse(args);
 if(name==='execute_approved_plan')return {operation:await execute(store,operationId)};
 if(name==='reconcile_operation')return {operation:await execute(store,operationId,true)};
 if(name==='get_operation'){const state=(await store.read()).data;const operation=state.operations.find(o=>o.id===operationId);if(!operation)throw new DomainError('NOT_FOUND','This operation does not belong to this workspace.');return {operation,evidence:operationEvidence(state,operation)};}
 throw new DomainError('UNKNOWN_TOOL','Unknown tool.');
}
